[project]
name = "snob-factor"
dynamic = ["version"]
description = "Mixture modelling by Minimum Message Length (MML) using Factor Snob"
authors = [
    { name = "Chris Wallace", email = "csw@cs.monash.edu.au"},
    { name = "Michel Fodje", email = "michel.fodje@lightsource.ca" },
]
maintainers = [
    { name = "Michel Fodje", email = "michel.fodje@lightsource.ca" },
]
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["MML", "Unsupervised Classification", "Machine Learning", "Snob", "Factor Analysis"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry]
packages = [{ include = "snob" }]
include = [{ path = "snob/_snob.so", format = "wheel" }]
build = "build.py"

classifiers = [
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Natural Language :: English",
    "Programming Language :: C",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
version = "0.0.0"

[tool.poetry.dependencies]
python = ">=3.11"
pandas = "*"
numpy = "*"
prettytable = "*"

[tool.poetry.urls]
Homepage = "https://github.com/michel4j/snob-factor"
documentation = "https://github.com/michel4j/snob-factor"
repository = "https://github.com/michel4j/snob-factor"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.0.0"

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
format = "{base}.{revision}{distance}"