name: Build and upload to PyPI

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          plugins: |
            poetry-dynamic-versioning
      - name: Build Wheel
        run: |
          poetry install --no-root
          poetry build --format wheel

      - uses: actions/upload-artifact@v4
        with:
          name: poetry-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: dist/*.whl

  build_wheels_manylinux:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          plugins: |
            poetry-dynamic-versioning
      - name: Build manylinux wheels
        uses: pypa/cibuildwheel@v2.20.0
        with:
          output-dir: dist
        env:
          CIBW_BUILD: "cp311-* cp312-* cp313-* cp314-*"
          CIBW_BEFORE_BUILD: "pip install poetry && poetry install"
      - uses: actions/upload-artifact@v4
        with:
          name: poetry-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: dist/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          plugins: |
            poetry-dynamic-versioning
      - name: Build Source Distribution
        run: |
          poetry install --no-root
          poetry build --format sdist
      - uses: actions/upload-artifact@v4
        with:
          name: poetry-sdist
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          # unpacks all poetry artifacts into dist/
          pattern: poetry-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
