name: Build and upload to PyPI

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Poetry
        run: |
          pipx install poetry
          pipx inject poetry "poetry-dynamic-versioning[plugin]"

      - name: Install dependencies
        run: poetry install --no-root
      
      - name: Build wheels
        run: poetry build -f wheel

      - uses: actions/upload-artifact@v4
        with:
          name: poetry-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: dist/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Poetry
        run: |
          pipx install poetry
          pipx inject poetry "poetry-dynamic-versioning[plugin]"

      - name: Build sdist
        run: poetry build -f sdist

      - uses: actions/upload-artifact@v4
        with:
          name: poetry-sdist
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          # unpacks all poetry artifacts into dist/
          pattern: poetry-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
