# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    tags: ["v*"]
  release:
    types: [ published ]

permissions:
  contents: read

jobs:

  build_wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version:  ${{ matrix.python-version }}

      - name: Setup pip
        run: |
           python -m pip install --upgrade pip setuptools wheel twine
           python -m pip install cibuildwheel

      - name: Build wheel
        run: python -m cibuildwheel --output-dir dist/

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}